### ISSUE TITLE
local variable 'links' referenced before assignment

### ISSUE THREAD

**Issue by chuoicu** [aboul3la/Sublist3r#108]
Process BaiduEnum-2:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "sublist3r.py", line 264, in run
    domain_list = self.enumerate()
  File "sublist3r.py", line 237, in enumerate
    links = self.extract_domains(resp)
  File "sublist3r.py", line 489, in extract_domains
    return links
UnboundLocalError: local variable 'links' referenced before assignment

**Comment by lianfeng30** [comment]
yes some problem

**Comment by persebek** [comment]
Also received the same error. Working on a pull request to fix.

**Comment by persebek** [comment]
Pull request #113 created to fix this issue.
