### ISSUE TITLE
bug??

### ISSUE THREAD

**Issue by huitc** [aboul3la/Sublist3r#143]
Virustotal: www.hellotesting.com
Process NetcraftEnum-7:
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "sublist3r.py", line 264, in run
    domain_list = self.enumerate()
  File "sublist3r.py", line 561, in enumerate
    cookies = self.get_cookies(resp.headers)
  File "sublist3r.py", line 553, in get_cookies
    cookies = self.create_cookies(headers['set-cookie'])
  File "sublist3r.py", line 548, in create_cookies
    cookies['netcraft_js_verification_response'] = hashlib.sha1(urllib.unquote(cookies_list[1])).hexdigest()
TypeError: Unicode-objects must be encoded before hashing
[-] Total Unique Subdomains Found: 1

Process NetcraftEnum-7:
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "sublist3r.py", line 264, in run
    domain_list = self.enumerate()
  File "sublist3r.py", line 561, in enumerate
    cookies = self.get_cookies(resp.headers)
  File "sublist3r.py", line 553, in get_cookies
    cookies = self.create_cookies(headers['set-cookie'])
  File "sublist3r.py", line 548, in create_cookies
    cookies['netcraft_js_verification_response'] = hashlib.sha1(urllib.unquote(cookies_list[1])).hexdigest()
TypeError: Unicode-objects must be encoded before hashing

_從我的 MI6，使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 發送。_

**Comment by huitc** [comment]
:+1:

**Comment by coolfoolunidentifiedhacker** [comment]
Process GoogleEnum-4:
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/storage/emulated/0/Download/Sublist3r-master/Sublist3r-master/sublist3r.py", line 264, in run
    domain_list = self.enumerate()
  File "/storage/emulated/0/Download/Sublist3r-master/Sublist3r-master/sublist3r.py", line 235, in enumerate
    if not self.check_response_errors(resp):
  File "/storage/emulated/0/Download/Sublist3r-master/Sublist3r-master/sublist3r.py", line 299, in check_response_errors
    if (type(resp) is str or type(resp) is unicode) and 'Our systems have detected unusual traffic' in resp:
NameError: name 'unicode' is not defined
HTTPSConnectionPool(host='dnsdumpster.com', port=443): Read timed out. (read timeout=25)
Process DNSdumpster-8:
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/storage/emulated/0/Download/Sublist3r-master/Sublist3r-master/sublist3r.py", line 264, in run
    domain_list = self.enumerate()
  File "/storage/emulated/0/Download/Sublist3r-master/Sublist3r-master/sublist3r.py", line 643, in enumerate
    self.extract_domains(post_resp)
  File "/storage/emulated/0/Download/Sublist3r-master/Sublist3r-master/sublist3r.py", line 655, in extract_domains
    results_tbl = tbl_regex.findall(resp)[0]
TypeError: expected string or bytes-like object



This error comes all the times
