### ISSUE TITLE
Process NetcraftEnum-7 Error

### ISSUE THREAD

**Issue by sidtechnical** [aboul3la/Sublist3r#147]
Seems like an old issue, but still bothering me!

Python 3.6.5, Python 2.7.15 -- pip 18.0

Process NetcraftEnum-7:
Traceback (most recent call last):
 ```
 File "/home/username/anaconda3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "sublist3r.py", line 264, in run
    domain_list = self.enumerate()
  File "sublist3r.py", line 561, in enumerate
    cookies = self.get_cookies(resp.headers)
  File "sublist3r.py", line 553, in get_cookies
    cookies = self.create_cookies(headers['set-cookie'])
  File "sublist3r.py", line 548, in create_cookies
    cookies['netcraft_js_verification_response'] = hashlib.sha1(urllib.unquote(cookies_list[1])).hexdigest()
TypeError: Unicode-objects must be encoded before hashing
```

**Comment by youshaoduo** [comment]
Unicode-objects must be encoded before hashing

**Comment by InfoSecRavindra** [comment]
Same error here.

**Comment by InfoSecRavindra** [comment]
Today I ran `sudo pip3 install -r requirements.txt` in my Ubuntu 18.04 and the error is gone.

`Python 3.6.7`
`pip 9.0.1`
