### ISSUE TITLE
('Connection aborted.', BadStatusLine("''",)) Process NetcraftEnum-7:

### ISSUE THREAD

**Issue by hktalent** [aboul3la/Sublist3r#148]
```
#py2 sublist3r.py -d gov.cn -o /mysvn/all_gov.cn.txt
('Connection aborted.', BadStatusLine("''",))
Process NetcraftEnum-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "sublist3r.py", line 264, in run
    domain_list = self.enumerate()
  File "sublist3r.py", line 566, in enumerate
    if 'Next page' not in resp:
TypeError: argument of type 'int' is not iterable

git pull

Traceback (most recent call last):
  File "sublist3r.py", line 985, in <module>
    interactive()
  File "sublist3r.py", line 982, in interactive
    res = main(domain, threads, savefile, ports, silent=False, verbose=verbose, enable_bruteforce=enable_bruteforce, engines=engines)
  File "sublist3r.py", line 952, in main
    write_file(savefile, subdomains)
  File "sublist3r.py", line 107, in write_file
    with open(str(filename), 'wt',encoding='utf-8') as f:
TypeError: 'encoding' is an invalid keyword argument for this function


('Connection aborted.', BadStatusLine("''",))
Process NetcraftEnum-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "sublist3r.py", line 264, in run
    domain_list = self.enumerate()
  File "sublist3r.py", line 567, in enumerate
    if 'Next page' not in resp:
TypeError: argument of type 'int' is not iterable
```

**Comment by amustaque97** [comment]
Hey, @hktalent after removing encoding block from line no 107 it is working for python2 as well.Sorry for the bug. ^_^
![gitupload](https://user-images.githubusercontent.com/21127788/46972898-4c39b400-d0dd-11e8-9a3d-029a5439152c.png)
