### ISSUE TITLE
object has no attribute 'headers'

### ISSUE THREAD

**Issue by aiwennba** [aboul3la/Sublist3r#150]
[-] Searching now in Baidu..
[-] Searching now in Yahoo..
[-] Searching now in Google..
[-] Searching now in Bing..
[-] Searching now in Ask..
[-] Searching now in Netcraft..
[-] Searching now in DNSdumpster..
[-] Searching now in Virustotal..
[-] Searching now in ThreatCrowd..
[-] Searching now in SSL Certificates..
[-] Searching now in PassiveDNS..
[SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661)
Process NetcraftEnum-7:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "sublist3r.py", line 264, in run
    domain_list = self.enumerate()
  File "sublist3r.py", line 562, in enumerate
    cookies = self.get_cookies(resp.headers)
AttributeError: 'NoneType' object has no attribute 'headers'

**Comment by end1an** [comment]
Use this command
`pip install --upgrade certifi`
