### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by huitc** [aboul3la/Sublist3r#151]
`$ python sublist3r.py -v -d ashome.com`
Traceback (most recent call last):
  File "sublist3r.py", line 21, in <module>
    from subbrute import subbrute
  File "/data/data/com.termux/files/home/sublist/subbrute/subbrute.py", line 18, in <module>
    import dns.resolver
ModuleNotFoundError: No module named 'dns.resolver'

**Comment by ASKWares** [comment]
i can't include sublist3r in my django app
may i have your help ?

**Comment by obiwankenoobi** [comment]
any updates on that? I have the same issue

**Comment by kamalakkannan1984** [comment]
any updates on that? I have the same issue

**Comment by obiwankenoobi** [comment]
@kamalakkannan1984 I had a conflict with my python versions and it aint run it with the one I wanted it to. I deleted any other versions so it will absolutely for sure start it with the one I want (2.7 i think) and it worked.

**Comment by kamalakkannan1984** [comment]
Also worked for me

import sublist3r  to change from sublist3r import sublist3r

 subdomains = sublist3r.main('yahoo.com', 40, 'yahoo_subdomains.txt', ports= None, silent=False, verbose= False, enable_bruteforce= False, engines=None)
    return HttpResponse(json.dumps(subdomains));

Also, Need

>>pip install dnspython
>>pip install requests

**Comment by barathraj-hack** [comment]
$ python sublist3r.py -v -d ashome.com
Traceback (most recent call last):
File "sublist3r.py", line 21, in
from subbrute import subbrute
File "/data/data/com.termux/files/home/sublist/subbrute/subbrute.py", line 18, in
import dns.resolver
ModuleNotFoundError: No module named 'dns.resolver'

**Comment by NeilSCGH** [comment]
any updates on that? I have the same issue

**Comment by satya703951** [comment]
same issue
