### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by huitc** [aboul3la/Sublist3r#152]
`C:\Users\fku\Documents\fku>sublist3r.py -v -d fku.com`
[-] Searching now in PassiveDNS..
HTTPSConnectionPool(host='dnsdumpster.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)'),))
Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Users\fku\Documents\fku\sublist3r.py", line 264, in run
    domain_list = self.enumerate()
  File "C:\Users\fku\Documents\fku\sublist3r.py", line 639, in enumerate
    token = self.get_csrftoken(resp)
  File "C:\Users\fku\Documents\fku\sublist3r.py", line 634, in get_csrftoken
    token = csrf_regex.findall(resp)[0]
TypeError: expected string or buffer

HTTPSConnectionPool(host='www.virustotal.com', port=443): Max retries exceeded with url: /en/domain/fku.com/information/ (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)'),))
HTTPSConnectionPool(host='searchdns.netcraft.com', port=443): Max retries exceeded with url: /?restriction=site+ends+with&host=example.com (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)'),))
Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Users\fku\Documents\fku\sublist3r.py", line 264, in run
    domain_list = self.enumerate()
  File "C:\Users\fku\Documents\fku\sublist3r.py", line 561, in enumerate
    cookies = self.get_cookies(resp.headers)
AttributeError: 'NoneType' object has no attribute 'headers'

`C:\Users\fku\Documents\fku>`

**Comment by huitc** [comment]
`python3 sublist3r.py -v -d xxxxx.com -o xxxxx.txt`
```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "sublist3r.py", line 264, in run
    domain_list = self.enumerate()
  File "sublist3r.py", line 561, in enumerate
    cookies = self.get_cookies(resp.headers)
  File "sublist3r.py", line 553, in get_cookies
    cookies = self.create_cookies(headers['set-cookie'])
  File "sublist3r.py", line 548, in create_cookies
    cookies['netcraft_js_verification_response'] = hashlib.sha1(urllib.unquote(cookies_list[1])).hexdigest()
TypeError: Unicode-objects must be encoded before hashing
```

**Comment by h0ek** [comment]
[-] Searching now in PassiveDNS..
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)
Process NetcraftEnum-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "./sublist3r.py", line 268, in run
    domain_list = self.enumerate()
  File "./sublist3r.py", line 568, in enumerate
    cookies = self.get_cookies(resp.headers)
AttributeError: 'NoneType' object has no attribute 'headers'
