### ISSUE TITLE
Error running sublist3r

### ISSUE THREAD

**Issue by gbiagomba** [aboul3la/Sublist3r#158]
sublist3r -d REDACTED.com -v -t 10 -o sublist3r_output

                 ____        _     _ _     _   _____
                / ___| _   _| |__ | (_)___| |_|___ / _ __
                \___ \| | | | '_ \| | / __| __| |_ \| '__|
                 ___) | |_| | |_) | | \__ \ |_ ___) | |
                |____/ \__,_|_.__/|_|_|___/\__|____/|_|

                # Coded By Ahmed Aboul-Ela - @aboul3la
    
[-] Enumerating subdomains now for REDACTED.com
[-] verbosity is enabled, will show the subdomains results in realtime
[-] Searching now in Baidu..
[-] Searching now in Yahoo..
[-] Searching now in Google..
[-] Searching now in Bing..
[-] Searching now in Ask..
[-] Searching now in Netcraft..
[-] Searching now in DNSdumpster..
[-] Searching now in Virustotal..
[-] Searching now in ThreatCrowd..
[-] Searching now in SSL Certificates..
[-] Searching now in PassiveDNS..
__str__ returned non-string (type Error)
Process AskEnum-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
Process DNSdumpster-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
Process BingEnum-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
    self.run()
  File "/usr/share/sublist3r/sublist3r", line 264, in run
  File "/usr/share/sublist3r/sublist3r", line 264, in run
    domain_list = self.enumerate()
    domain_list = self.enumerate()
  File "/usr/share/sublist3r/sublist3r", line 237, in enumerate
    links = self.extract_domains(resp)
  File "/usr/share/sublist3r/sublist3r", line 395, in extract_domains
    return links_list
UnboundLocalError: local variable 'links_list' referenced before assignment
  File "/usr/share/sublist3r/sublist3r", line 634, in enumerate
    token = self.get_csrftoken(resp)
  File "/usr/share/sublist3r/sublist3r", line 629, in get_csrftoken
    token = csrf_regex.findall(resp)[0]
TypeError: expected string or buffer
    self.run()
  File "/usr/share/sublist3r/sublist3r", line 264, in run
    domain_list = self.enumerate()
  File "/usr/share/sublist3r/sublist3r", line 237, in enumerate
    links = self.extract_domains(resp)
  File "/usr/share/sublist3r/sublist3r", line 443, in extract_domains
    return links_list
UnboundLocalError: local variable 'links_list' referenced before assignment
__str__ returned non-string (type Error)
Process GoogleEnum-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/share/sublist3r/sublist3r", line 264, in run
    domain_list = self.enumerate()
  File "/usr/share/sublist3r/sublist3r", line 235, in enumerate
    if not self.check_response_errors(resp):
  File "/usr/share/sublist3r/sublist3r", line 298, in check_response_errors
    if 'Our systems have detected unusual traffic' in resp:
TypeError: argument of type 'int' is not iterable
__str__ returned non-string (type Error)
Process NetcraftEnum-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/share/sublist3r/sublist3r", line 264, in run
    domain_list = self.enumerate()
  File "/usr/share/sublist3r/sublist3r", line 557, in enumerate
    cookies = self.get_cookies(resp.headers)
AttributeError: 'NoneType' object has no attribute 'headers'
Process BaiduEnum-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/share/sublist3r/sublist3r", line 264, in run
    domain_list = self.enumerate()
  File "/usr/share/sublist3r/sublist3r", line 237, in enumerate
    links = self.extract_domains(resp)
  File "/usr/share/sublist3r/sublist3r", line 489, in extract_domains
    return links
UnboundLocalError: local variable 'links' referenced before assignment

**Comment by Princeman2** [comment]
Hi gbiagomba, I ran into this problem too but I can see that you have closed it, any solution to it ?

**Comment by gbiagomba** [comment]
@Princeman2  Did you install the dependencies?
```
pip3 install -r requirements.txt --user
```
