### ISSUE TITLE
dnsdumpster timeout

### ISSUE THREAD

**Issue by dzhenway** [aboul3la/Sublist3r#173]
HTTPSConnectionPool(host='dnsdumpster.com', port=443): Read timed out. (read timeout=25)
Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "C:\Python27\Sublist3r-master\sublist3r.py", line 264, in run
    domain_list = self.enumerate()
  File "C:\Python27\Sublist3r-master\sublist3r.py", line 643, in enumerate
    self.extract_domains(post_resp)
  File "C:\Python27\Sublist3r-master\sublist3r.py", line 655, in extract_domains
    results_tbl = tbl_regex.findall(resp)[0]
TypeError: expected string or buffer

**Comment by hughesdg** [comment]
Did you ever get a fix for this? I have the same issue. It was working until recently.
