### ISSUE TITLE
Netcraft error - looks like Netcraft have changed something

### ISSUE THREAD

**Issue by Teicu** [aboul3la/Sublist3r#18]
Process NetcraftEnum-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "sublist3r.py", line 461, in run
    domain_list = self.enumerate()
  File "sublist3r.py", line 506, in enumerate
    cookies = self.create_cookies(resp.headers['set-cookie'])
  File "/usr/local/lib/python2.7/dist-packages/requests/structures.py", line 56, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'set-cookie'
[!] Error: Google probably now is blocking our requests
[~] Finished now the Google Enumeration ...

**Comment by aboul3la** [comment]
This was fixed a while ago, please update to the latest version on github

Execute the following command on your terminal:
``` git pull ```

or clone the repo again:
```  git clone https://github.com/aboul3la/Sublist3r.git ```
