### ISSUE TITLE
solve this error 

### ISSUE THREAD

**Issue by shadihh9** [aboul3la/Sublist3r#183]
HTTPSConnectionPool(host='dnsdumpster.com', port=443): Read timed out. (read timeout=25)
Process DNSdumpster-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "sublist3r.py", line 264, in run
    domain_list = self.enumerate()
  File "sublist3r.py", line 643, in enumerate
    self.extract_domains(post_resp)
  File "sublist3r.py", line 655, in extract_domains
    results_tbl = tbl_regex.findall(resp)[0]
TypeError: expected string or buffer

**Comment by AdriiiPRodri** [comment]
Hi @shadihh9,

This problem is solved as described [here](https://github.com/aboul3la/Sublist3r/issues/33#issuecomment-542613643). 

@aboul3la I suggest to add the changes to the master branch or if you want to avoid adding another dependency, the regex should be reviewed.
