### ISSUE TITLE
Process DNSdumpster-8 Error

### ISSUE THREAD

**Issue by MrMad0x0** [aboul3la/Sublist3r#189]
Process DNSdumpster-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/bin/sublister", line 264, in run
    domain_list = self.enumerate()
  File "/usr/bin/sublister", line 640, in enumerate
    token = self.get_csrftoken(resp)
  File "/usr/bin/sublister", line 635, in get_csrftoken
    token = csrf_regex.findall(resp)[0]
IndexError: list index out of range

**Comment by bdweix** [comment]
+1 seeing this issue as well when looking for subdomains

**Comment by mouanime04** [comment]
+2

**Comment by wha000tif** [comment]
sublist3r.py  line 638    

![image](https://user-images.githubusercontent.com/7933890/67264156-d7157180-f4dc-11e9-8027-1e5dc15b257a.png)

edit the function code as this
![image](https://user-images.githubusercontent.com/7933890/67264187-ef858c00-f4dc-11e9-9897-e30f4360121b.png)


on my pc , this is ok

**Comment by aboul3la** [comment]
Sorry for being late in resolving the issue. DNSDumpster recently has made a modification in their website which caused this error. It should be fixed now in latest commit 5d33d9f25a92cc3f91eb351cff2d7007c198fb44

Please update your Sublist3r version using command: `git pull`

**Comment by Sublist3r** [comment]
still same error after doing git pull...

HTTPSConnectionPool(host='dnsdumpster.com', port=443): Read timed out. (read timeout=25)
Process DNSdumpster-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "sublist3r.py", line 269, in run
    domain_list = self.enumerate()
  File "sublist3r.py", line 648, in enumerate
    self.extract_domains(post_resp)
  File "sublist3r.py", line 660, in extract_domains
    results_tbl = tbl_regex.findall(resp)[0]
TypeError: expected string or buffer
