### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by M0dred** [aboul3la/Sublist3r#192]
Mac OS
Python 3.7.4

uname -a 
19.0.0 Darwin Kernel Version 19.0.0: Wed Sep 25 20:18:50 PDT 2019; root:xnu-6153.11.26~2/RELEASE_X86_64 x86_64

HTTPSConnectionPool(host='dnsdumpster.com', port=443): Read timed out. (read timeout=25)
Process DNSdumpster-8:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "sublist3r.py", line 269, in run
    domain_list = self.enumerate()
  File "sublist3r.py", line 648, in enumerate
    self.extract_domains(post_resp)
  File "sublist3r.py", line 660, in extract_domains
    results_tbl = tbl_regex.findall(resp)[0]
TypeError: expected string or bytes-like object

**Comment by LucasBaizer** [comment]
see #33
