### ISSUE TITLE
Process DNSdumpster-8:IndexError: list index out of range

### ISSUE THREAD

**Issue by hktalent** [aboul3la/Sublist3r#198]
```
Process DNSdumpster-8:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.5/dist-packages/sublist3r.py", line 264, in run
    domain_list = self.enumerate()
  File "/usr/local/lib/python3.5/dist-packages/sublist3r.py", line 640, in enumerate
    token = self.get_csrftoken(resp)
  File "/usr/local/lib/python3.5/dist-packages/sublist3r.py", line 635, in get_csrftoken
    token = csrf_regex.findall(resp)[0]
IndexError: list index out of range
```

**Comment by marcelo321** [comment]
this isn't fixed? i keep getting this same error.

**Comment by fitzpr** [comment]
I've patched the CSRF code as per the diff but this issue is still occuring?
