### ISSUE TITLE
Error when using socks proxy in kali linux

### ISSUE THREAD

**Issue by sundaysec** [aboul3la/Sublist3r#201]
Here is the output
Unable to determine SOCKS version from socks://12.345.678.23:8080/
Unable to determine SOCKS version from socks://12.345.678.23:8080/
Unable to determine SOCKS version from socks://12.345.678.23:8080/
Process GoogleEnum-4:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "sublist3r.py", line 269, in run
    domain_list = self.enumerate()
  File "sublist3r.py", line 240, in enumerate
    if not self.check_response_errors(resp):
  File "sublist3r.py", line 304, in check_response_errors
    if (type(resp) is str or type(resp) is unicode) and 'Our systems have detected unusual traffic' in resp:
NameError: name 'unicode' is not defined
Process NetcraftEnum-7:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "sublist3r.py", line 269, in run
    domain_list = self.enumerate()
  File "sublist3r.py", line 567, in enumerate
    cookies = self.get_cookies(resp.headers)
AttributeError: 'NoneType' object has no attribute 'headers'
Process Virustotal-9:
Process DNSdumpster-8:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "sublist3r.py", line 269, in run
    domain_list = self.enumerate()
  File "sublist3r.py", line 645, in enumerate
    token = self.get_csrftoken(resp)
  File "sublist3r.py", line 640, in get_csrftoken
    token = csrf_regex.findall(resp)[0]
TypeError: expected string or bytes-like object
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "sublist3r.py", line 269, in run
    domain_list = self.enumerate()
  File "sublist3r.py", line 699, in enumerate
    resp = json.loads(resp)
  File "/usr/lib/python3.7/json/__init__.py", line 341, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not int
^CTraceback (most recent call last):
  File "sublist3r.py", line 1001, in <module>
    interactive()
  File "sublist3r.py", line 998, in interactive
    res = main(domain, threads, savefile, ports, silent=False, verbose=verbose, enable_bruteforce=enable_bruteforce, engines=engines)
  File "sublist3r.py", line 942, in main
    enum.join()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 140, in join
    res = self._popen.wait(timeout)
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 48, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
KeyboardInterrupt
Process BaiduEnum-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "sublist3r.py", line 269, in run
    domain_list = self.enumerate()
  File "sublist3r.py", line 254, in enumerate
    self.should_sleep()
  File "sublist3r.py", line 511, in should_sleep
    time.sleep(random.randint(2, 5))
KeyboardInterrupt

**Comment by palejaga** [comment]
Bounty ng Seguridad ng Seguridad

**Comment by palejaga** [comment]
https://help.zenhub.com/support/solutions/articles/43000539833-how-each-member-of-the-team-can-use-zenhub-roadmaps

**Comment by palejaga** [comment]
https://id.oppo.com/account_faq.html?language=en-US
