### ISSUE TITLE
Error in collecting data form the Dnsdumpstar-8

### ISSUE THREAD

**Issue by A2hari** [aboul3la/Sublist3r#204]
<h2>The Dnsdumpstar-8 module is not working </h2>

Process DNSdumpster-8:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3/dist-packages/sublist3r.py", line 264, in run
    domain_list = self.enumerate()
  File "/usr/lib/python3/dist-packages/sublist3r.py", line 640, in enumerate
    token = self.get_csrftoken(resp)
  File "/usr/lib/python3/dist-packages/sublist3r.py", line 635, in get_csrftoken
    token = csrf_regex.findall(resp)[0]
IndexError: list index out of range

**Comment by nickbail3y** [comment]
I am also having this issue.

**Comment by marcelo321** [comment]
Same here!

**Comment by stevemcilwain** [comment]
same...
Process DNSdumpster-2:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3/dist-packages/sublist3r.py", line 264, in run
    domain_list = self.enumerate()
  File "/usr/lib/python3/dist-packages/sublist3r.py", line 640, in enumerate
    token = self.get_csrftoken(resp)
  File "/usr/lib/python3/dist-packages/sublist3r.py", line 635, in get_csrftoken
    token = csrf_regex.findall(resp)[0]
IndexError: list index out of range

**Comment by aboul3la** [comment]
Hi,

This issue has been resolved 3 months ago in commit 5d33d9f25a92cc3f91eb351cff2d7007c198fb44

Kindly ensure that you downloaded the latest update using: `git pull` command.

**Comment by abhi-jasud** [comment]
File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3/dist-packages/sublist3r.py", line 264, in run
    domain_list = self.enumerate()
  File "/usr/lib/python3/dist-packages/sublist3r.py", line 640, in enumerate
    token = self.get_csrftoken(resp)
  File "/usr/lib/python3/dist-packages/sublist3r.py", line 635, in get_csrftoken
    token = csrf_regex.findall(resp)[0]
IndexError: list index out of range

please fix it
