### ISSUE TITLE
subbrute too slow!

### ISSUE THREAD

**Issue by marcelo321** [aboul3la/Sublist3r#206]
i was trying to use the subbrute mode to bruteforce subdomains and realized it was way too slow. i shortened the wordlist to 1k subdomains and runned it again at 100 threads (-t 100) and still 15 minutes and keeps going...

Is there any way to speed up this? what about the resolvers.txt? can i update it somehow? what type of resolvers and where should i look for them?

**Comment by marcelo321** [comment]
update:

It is not working at all, i tried changed names.txt to only 3 subdomains and it freezes there and doesn't do anything.
i get this error before the brute-force starts but it doesn't do anything with the normal subdomain enumeration.

Process DNSdumpster-8:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "sublist3r.py", line 264, in run
    domain_list = self.enumerate()
  File "sublist3r.py", line 640, in enumerate
    token = self.get_csrftoken(resp)
  File "sublist3r.py", line 635, in get_csrftoken
    token = csrf_regex.findall(resp)[0]
IndexError: list index out of range

**Comment by nsrauf** [comment]
Same here! I tried a wordlist of 10 words but it never ends.

Looks like it picks up the default wordlists /path/sublist3r/subbrute/name.txt (i tried using my own name.txt with 10 words but still no luck)

Any help ?

**Comment by aboul3la** [comment]
Hi,

Thanks for reporting this issue. 

This issue occurred because the `resolvers.txt` list used by subbrute was outdated and most of the DNS servers IP Addresses were down. 

 I just updated the resolvers.txt file and the issue should be resolved now.

Kindly pull the latest update using `git pull` command.

**Comment by nsrauf** [comment]
Hey!!

Sorry, but I don't think this issues is resolved. It is still taking hours and never ends for a very small subdomain list.

my `git pull` said "already up to date"

Would you mind looking into it.

Thanks!
