### ISSUE TITLE
ImportError: No module named parse

### ISSUE THREAD

**Issue by tuszyn** [aboul3la/Sublist3r#208]
Traceback (most recent call last):
  File "sublist3r.py", line 21, in <module>
    from subbrute import subbrute
  File "/home/myname/Downloads/Programs/Sublist3r/subbrute/subbrute.py", line 18, in <module>
    import dns.resolver
  File "build/bdist.linux-x86_64/egg/dns/resolver.py", line 20, in <module>
ImportError: No module named parse

**Comment by coosamatt** [comment]
Where you able to resolve this? I am having the same issue now.
