### ISSUE TITLE
error code

### ISSUE THREAD

**Issue by UdaryanDotCom** [aboul3la/Sublist3r#218]
Traceback (most recent call last):
  File "sublist3r.py", line 21, in <module>
    from subbrute import subbrute
  File "/root/Downloads/Sublist3r/subbrute/subbrute.py", line 18, in <module>
    import dns.resolver
ModuleNotFoundError: No module named 'dns'

error  i have install but error came out

**Comment by brunoffsp** [comment]
The same happened to me and in my case I was expecting sublist3r to run on python3, the version that I had installed all dependencies, but  in my environment `python` was pointing to python2.

If that is your case, try to be explicit by running it `python3 sublistr3r.py` instead of relying on the script's shebang environment choice when running just `./sublistr3`.

If that solves for you, you can either keep running it this way or update the shebang on the first line of sublistr3.py from `#!/usr/bin/env python` to `#!/usr/bin/env python3` or change your environment, making `python` point to python3
