### ISSUE TITLE
Dnsdumpster Read timed out

### ISSUE THREAD

**Issue by paradiseduo** [aboul3la/Sublist3r#239]
```bash
HTTPSConnectionPool(host='dnsdumpster.com', port=443): Read timed out. (read timeout=25)
Process DNSdumpster-8:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "sublist3r.py", line 269, in run
    domain_list = self.enumerate()
  File "sublist3r.py", line 652, in enumerate
    self.extract_domains(post_resp)
  File "sublist3r.py", line 664, in extract_domains
    results_tbl = tbl_regex.findall(resp)[0]
TypeError: expected string or buffer
```

**Comment by amustaque97** [comment]
Hey @paradiseduo please check your internet connection and try again. If it is working fine. Please close this issue. 
- Have a nice day :)
