### ISSUE TITLE
NameError: name 'unicode' is not defined

### ISSUE THREAD

**Issue by hongyi-zhao** [aboul3la/Sublist3r#249]
Hi,

On Ubuntu 20.04, I try to use Sublist3r git master version with python 3.8.3, and I meet the following issue:

```
$ python sublist3r.py -d baidu.com

                 ____        _     _ _     _   _____
                / ___| _   _| |__ | (_)___| |_|___ / _ __
                \___ \| | | | '_ \| | / __| __| |_ \| '__|
                 ___) | |_| | |_) | | \__ \ |_ ___) | |
                |____/ \__,_|_.__/|_|_|___/\__|____/|_|

                # Coded By Ahmed Aboul-Ela - @aboul3la
    
[-] Enumerating subdomains now for baidu.com
[-] Searching now in Baidu..
[-] Searching now in Yahoo..
[-] Searching now in Google..
[-] Searching now in Bing..
[-] Searching now in Ask..
[-] Searching now in Netcraft..
[-] Searching now in DNSdumpster..
[-] Searching now in Virustotal..
[-] Searching now in ThreatCrowd..
[-] Searching now in SSL Certificates..
[-] Searching now in PassiveDNS..
sublist3r.py:614: DeprecationWarning: please use dns.resolver.Resolver.resolve() instead
  ip = Resolver.query(host, 'A')[0].to_text()
Process GoogleEnum-4:
Traceback (most recent call last):
  File "/home/werner/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "sublist3r.py", line 268, in run
    domain_list = self.enumerate()
  File "sublist3r.py", line 240, in enumerate
    if not self.check_response_errors(resp):
  File "sublist3r.py", line 303, in check_response_errors
    if (type(resp) is str or type(resp) is unicode) and 'Our systems have detected unusual traffic' in resp:
NameError: name 'unicode' is not defined
HTTPConnectionPool(host='searchdns.netcraft.com', port=80): Read timed out. (read timeout=25)
Process NetcraftEnum-7:
Traceback (most recent call last):
  File "/home/werner/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "sublist3r.py", line 268, in run
    domain_list = self.enumerate()
  File "sublist3r.py", line 573, in enumerate
    if 'Next Page' not in resp:
TypeError: argument of type 'int' is not iterable

```

Any hints for this problem?

Regards

**Comment by KrystianLi** [comment]
I have some

**Comment by Ky9oss** [comment]
I have same
