### ISSUE TITLE
TypeError: argument of type 'int' is not iterable

### ISSUE THREAD

**Issue by hongyi-zhao** [aboul3la/Sublist3r#250]
The environment is Ubuntu 20.04, python 3.8.3, and git master version of Sublist3r. I meet the following problem:

```
 $ python sublist3r.py -d mit.edu

                 ____        _     _ _     _   _____
                / ___| _   _| |__ | (_)___| |_|___ / _ __
                \___ \| | | | '_ \| | / __| __| |_ \| '__|
                 ___) | |_| | |_) | | \__ \ |_ ___) | |
                |____/ \__,_|_.__/|_|_|___/\__|____/|_|

                # Coded By Ahmed Aboul-Ela - @aboul3la
    
[-] Enumerating subdomains now for mit.edu
[-] Searching now in Baidu..
[-] Searching now in Yahoo..
[-] Searching now in Google..
[-] Searching now in Bing..
[-] Searching now in Ask..
[-] Searching now in Netcraft..
[-] Searching now in DNSdumpster..
[-] Searching now in Virustotal..
[-] Searching now in ThreatCrowd..
[-] Searching now in SSL Certificates..
[-] Searching now in PassiveDNS..
sublist3r.py:614: DeprecationWarning: please use dns.resolver.Resolver.resolve() instead
  ip = Resolver.query(host, 'A')[0].to_text()
[!] Error: Virustotal probably now is blocking our requests
Process GoogleEnum-4:
Traceback (most recent call last):
  File "/home/werner/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "sublist3r.py", line 268, in run
    domain_list = self.enumerate()
  File "sublist3r.py", line 240, in enumerate
    if not self.check_response_errors(resp):
  File "sublist3r.py", line 303, in check_response_errors
    if (type(resp) is str or type(resp) is unicode) and 'Our systems have detected unusual traffic' in resp:
NameError: name 'unicode' is not defined
HTTPSConnectionPool(host='searchdns.netcraft.com', port=443): Read timed out.
Process NetcraftEnum-7:
Traceback (most recent call last):
  File "/home/werner/.pyenv/versions/3.8.3/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "sublist3r.py", line 268, in run
    domain_list = self.enumerate()
  File "sublist3r.py", line 573, in enumerate
    if 'Next Page' not in resp:
TypeError: argument of type 'int' is not iterable
```

Any hints for this problem?

Regards

**Comment by DevinCarpenter** [comment]
Hey, try installing the requirements.txt file requirements again:

`pip install argparse`
`pip install dnspython`
`pip install requests`

I know this is a late answer but it doesn't seem like this repo is very lively for help. Program works well when it does work though.
