### ISSUE TITLE
Not able to run Sublist3r in kali below errror occure

### ISSUE THREAD

**Issue by vishaldp** [aboul3la/Sublist3r#258]
/Sublist3r# python sublist3r.py -h
Traceback (most recent call last):
  File "sublist3r.py", line 21, in <module>
    from subbrute import subbrute
  File "/root/Sublist3r/subbrute/subbrute.py", line 18, in <module>
    import dns.resolver
  File "build/bdist.linux-x86_64/egg/dns/resolver.py", line 19, in <module>
ImportError: No module named parse

**Comment by jr1221** [comment]
Try using python3 instead of python.

**Comment by RoninNakomoto** [comment]
try running it properly inside a python3 environment (that you'll have to create). These are python errors not tool errors.
