### ISSUE TITLE
Attribute Error 

### ISSUE THREAD

**Issue by ghost** [aboul3la/Sublist3r#287]
`[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)
Process NetcraftEnum-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/root/tools/Sublist3r/sublist3r.py", line 268, in run
    domain_list = self.enumerate()
  File "/root/tools/Sublist3r/sublist3r.py", line 568, in enumerate
    cookies = self.get_cookies(resp.headers)
AttributeError: 'NoneType' object has no attribute 'headers'`

I have python 2.7 and the latest edition of python and I installed it from the installation steps on this repository. Not sure what the issue seems to be here. The tool still works but it would be nice if I didn't have to see that issue when I run it.

**Comment by sdiggles** [comment]
I am getting something similar, on Python 3.8:
```
Exception in thread Thread-6:
Traceback (most recent call last):
  File "\AppData\Local\Programs\Python\Python38-32\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "\venv\lib\site-packages\sublist3r.py", line 268, in run
    domain_list = self.enumerate()
  File "\venv\lib\site-packages\sublist3r.py", line 568, in enumerate
    cookies = self.get_cookies(resp.headers)
AttributeError: 'NoneType' object has no attribute 'headers'
```

**Comment by ghost** [comment]
> I am getting something similar, on Python 3.8:
> 
> ```
> Exception in thread Thread-6:
> Traceback (most recent call last):
>   File "\AppData\Local\Programs\Python\Python38-32\lib\threading.py", line 932, in _bootstrap_inner
>     self.run()
>   File "\venv\lib\site-packages\sublist3r.py", line 268, in run
>     domain_list = self.enumerate()
>   File "\venv\lib\site-packages\sublist3r.py", line 568, in enumerate
>     cookies = self.get_cookies(resp.headers)
> AttributeError: 'NoneType' object has no attribute 'headers'
> ```

Really strange, I have only noticed this within the past couple months so maybe it has something to do with the latest update or something needs to be fixed?

**Comment by RoninNakomoto** [comment]
you're probably using the wrong python version or broke a dependency. the tool is fine under python3.
How are u running the tool.
Please create a proper python virtual environment to avoid dependency and python problems.

**Comment by RoninNakomoto** [comment]
@BenBencsik @sdiggles 

please tell me the steps of how you are running the tool (including commands used) to get those errors.
