### ISSUE TITLE
SSLError

### ISSUE THREAD

**Issue by hackping** [aboul3la/Sublist3r#294]
HTTPSConnectionPool(host='dnsdumpster.com', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLError('_ssl.c:645: The handshake operation timed out',),))
Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "sublist3r.py", line 268, in run
    domain_list = self.enumerate()
  File "sublist3r.py", line 647, in enumerate
    token = self.get_csrftoken(resp)
  File "sublist3r.py", line 641, in get_csrftoken
    token = csrf_regex.findall(resp)[0]
TypeError: expected string or buffer

**Comment by DevinCarpenter** [comment]
Hey - you aren't getting the same error I was, but maybe try running the sublist3r.py script directly. Explained in my other answer here. 

https://github.com/aboul3la/Sublist3r/issues/317#issuecomment-923192977
