### ISSUE TITLE
[!] Error: Virustotal probably now is blocking our requests怎么解决？

### ISSUE THREAD

**Issue by sunyiwk** [aboul3la/Sublist3r#297]
`               ____        _     _ _     _   _____
                / ___| _   _| |__ | (_)___| |_|___ / _ __
                \___ \| | | | '_ \| | / __| __| |_ \| '__|
                 ___) | |_| | |_) | | \__ \ |_ ___) | |
                |____/ \__,_|_.__/|_|_|___/\__|____/|_|

                # Coded By Ahmed Aboul-Ela - @aboul3la
    
[-] Enumerating subdomains now for aqlab.cn
[-] Searching now in Baidu..
[-] Searching now in Yahoo..
[-] Searching now in Google..
[-] Searching now in Bing..
[-] Searching now in Ask..
[-] Searching now in Netcraft..
[-] Searching now in DNSdumpster..
[-] Searching now in Virustotal..
[-] Searching now in ThreatCrowd..
[-] Searching now in SSL Certificates..
[-] Searching now in PassiveDNS..
Process GoogleEnum-4:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/root/Sublist3r/sublist3r.py", line 268, in run
    domain_list = self.enumerate()
  File "/root/Sublist3r/sublist3r.py", line 240, in enumerate
    if not self.check_response_errors(resp):
  File "/root/Sublist3r/sublist3r.py", line 303, in check_response_errors
    if (type(resp) is str or type(resp) is unicode) and 'Our systems have detected unusual traffic' in resp:
NameError: name 'unicode' is not defined
[!] Error: Virustotal probably now is blocking our requests
`

**Comment by glaucusec** [comment]
Cannot find a solution? Same issue here.

**Comment by glaucusec** [comment]
Any updates?

**Comment by garvitv14** [comment]
I'm facing the same situation !!! ANY UPDATES???
