### ISSUE TITLE
Error in Yahoo

### ISSUE THREAD

**Issue by elvinguitar** [aboul3la/Sublist3r#30]
Got the following error when using your latest copy of sublist3r:

```
Process YahooEnum-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "sublist3r.py", line 205, in run
    domain_list = self.enumerate()
  File "sublist3r.py", line 178, in enumerate
    links = self.extract_domains(resp)
  File "sublist3r.py", line 290, in extract_domains
    return links_list
UnboundLocalError: local variable 'links_list' referenced before assignment
```

**Comment by aboul3la** [comment]
Thanks  @elvinguitar for reporting this. I'm gonna take a look and fix it very soon.

**Comment by aboul3la** [comment]
This bug should be fixed now in the latest release.
