### ISSUE TITLE
error No JSON object could be decoded 

### ISSUE THREAD

**Issue by Archurcl4w** [aboul3la/Sublist3r#312]
I have this error when running sublist3r each time  :

Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "sublist3r.py", line 269, in run
    domain_list = self.enumerate()
  File "sublist3r.py", line 699, in enumerate
    resp = json.loads(resp)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

Kindly provide me any fix or solutions for it

**Comment by amustaque97** [comment]
Hi all, I will be looking into this and will keep posted with the updates.

**Comment by Archurcl4w** [comment]
Ok. Thanks .

**Comment by amustaque97** [comment]
Hi, @Archurcl4w can you please share steps to reproduce this error?

**Comment by amustaque97** [comment]
Hi, @Archurcl4w I'm not able to reproduce this error.
![Screenshot from 2021-05-12 05-01-17](https://user-images.githubusercontent.com/21127788/117898540-ca38b880-b2e2-11eb-9dfd-699340e06b96.png)

**Comment by YzaSoLong** [comment]
l also have the same problem,and my os is windows.

**Comment by amustaque97** [comment]
@YzaSoLong  can you please share what python version you're using? What command did you run on your system?

Regards

**Comment by RoninNakomoto** [comment]
@YzaSoLong @amustaque97 @Archurcl4w https://github.com/RoninNakomoto/Sublist3r2
this works
