### ISSUE TITLE
Https connection pool

### ISSUE THREAD

**Issue by Mayor294** [aboul3la/Sublist3r#332]
HTTPSConnectionPool(host='dnsdumpster.com', port=443): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x7171dabdf0>, 'Connection to dnsdumpster.com timed out. (connect timeout=25)'))                                                  Process DNSdumpster-8:
Traceback (most recent call last):                           File "/usr/lib/python3.10/multiprocessing/process.py", line 315, in _bootstrap                                          self.run()
  File "/usr/lib/python3/dist-packages/sublist3r.py", line 269, in run
    domain_list = self.enumerate()                           File "/usr/lib/python3/dist-packages/sublist3r.py", line 649, in enumerate                                              token = self.get_csrftoken(resp)
  File "/usr/lib/python3/dist-packages/sublist3r.py", line 644, in get_csrftoken
    token = csrf_regex.findall(resp)[0]                    TypeError: expected string or bytes-like object

**Comment by JPwnage** [comment]
Have you tried this solution here https://github.com/aboul3la/Sublist3r/issues/33#issuecomment-542613643
I have tried it but it did not work for me.
