### ISSUE TITLE
ImportError: cannot import name 'Mapping' from 'collections'

### ISSUE THREAD

**Issue by b33fsup3m3** [aboul3la/Sublist3r#347]
┌──(root㉿d3m0n)-[/home/d3m0n/Sublist3r]
└─# python2 sublist3r.py
Traceback (most recent call last):
  File "sublist3r.py", line 21, in <module>
    from subbrute import subbrute
  File "/home/d3m0n/Sublist3r/subbrute/subbrute.py", line 18, in <module>
    import dns.resolver
ImportError: No module named dns.resolver

┌──(root㉿d3m0n)-[/home/d3m0n/Sublist3r]
└─# python3 sublist3r.py -d example.com
Traceback (most recent call last):
  File "/home/d3m0n/Sublist3r/sublist3r.py", line 23, in <module>
    import requests
  File "/usr/local/lib/python3.10/dist-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/local/lib/python3.10/dist-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connectionpool.py", line 29, in <module>
    from .connection import (
  File "/usr/local/lib/python3.10/dist-packages/urllib3/connection.py", line 39, in <module>
    from .util.ssl_ import (
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/__init__.py", line 3, in <module>
    from .connection import is_connection_dropped
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/connection.py", line 3, in <module>
    from .wait import wait_for_read
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/wait.py", line 1, in <module>
    from .selectors import (
  File "/usr/local/lib/python3.10/dist-packages/urllib3/util/selectors.py", line 14, in <module>
    from collections import namedtuple, Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

i allready tried to install sublister with apt-get but i still get the same error:

ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

**Comment by francodevel** [comment]
Holy crap! I've been trying to solve this but no success. Same error. Some places say that that class Mapping, it's in collections.abc, not collections alone. How did you solve it? Any suggestions? I need this tool. Thanks for anything.

**Comment by harpreet1131** [comment]
i have the same issue , i have tried everything but all in vain , i think last solution to this is changing to older versions of python , i have not tested it , but i think it will work

**Comment by francodevel** [comment]
> i have the same issue , i have tried everything but all in vain , i think last solution to this is changing to older versions of python , i have not tested it , but i think it will work

I installed python3.7 and it's working fine. I had to compile it. Took a short time to build, so it's a good thing to install it that way.
It's because python3.7 is the last version where you can find this import. Best luck! Try it.
