### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by deepansh39** [aboul3la/Sublist3r#354]
sudo python3 sublist3r.py -h
Traceback (most recent call last):
  File "/home/hackion/tools/Sublist3r/sublist3r.py", line 21, in <module>
    from subbrute import subbrute
  File "/home/hackion/tools/Sublist3r/subbrute/subbrute.py", line 18, in <module>
    import dns.resolver
  File "/usr/lib/python3/dist-packages/dns/resolver.py", line 38, in <module>
    import dns.query
  File "/usr/lib/python3/dist-packages/dns/query.py", line 52, in <module>
    import httpx
  File "/usr/local/lib/python3.10/dist-packages/httpx-1.0.0b0-py3.10.egg/httpx/__init__.py", line 2, in <module>
    from ._api import delete, get, head, options, patch, post, put, request, stream
  File "/usr/local/lib/python3.10/dist-packages/httpx-1.0.0b0-py3.10.egg/httpx/_api.py", line 4, in <module>
    from ._client import Client
  File "/usr/local/lib/python3.10/dist-packages/httpx-1.0.0b0-py3.10.egg/httpx/_client.py", line 30, in <module>
    from ._transports.default import AsyncHTTPTransport, HTTPTransport
  File "/usr/local/lib/python3.10/dist-packages/httpx-1.0.0b0-py3.10.egg/httpx/_transports/default.py", line 92, in <module>
    httpcore.CloseError: CloseError,
AttributeError: module 'httpcore' has no attribute 'CloseError'

**Comment by deepansh39** [comment]
Ok guys i solved this error now my tool is running if someone else face this kind of issue you can counter with the help this tactic python3.11 sublist3r.py -h and it work 
![sublist3r](https://user-images.githubusercontent.com/47888093/213435588-e5b8262e-f974-4e13-98ad-94007bd3ad0d.png)

**Comment by 0mamii** [comment]
i have same issue, please help, 
![image](https://github.com/aboul3la/Sublist3r/assets/135441085/b0a907dc-a720-4120-a39e-d5e8041260fc)

**Comment by 0mamii** [comment]
> i have same issue, please help, ![image](https://user-images.githubusercontent.com/135441085/248314502-b0a907dc-a720-4120-a39e-d5e8041260fc.png)

fixed after installing httpcore 0.12.3
