### ISSUE TITLE
the tools does not work I am not getting any subdomain

### ISSUE THREAD

**Issue by codefaztaz** [aboul3la/Sublist3r#357]
in line 933 I have deleted virustotal from the code but. it does not work yet.

I run sudo python3 sublist3r.py -d example.com but I dont get any result

**Comment by aravael** [comment]
Confirmed. The tool doesn't provide any results. 
`python3 sublist3r.py -d godaddy.com`
@aboul3la could you please provide any feedback the tool is maintained and whether the issues are temporary?

**Comment by 0xK3on** [comment]
same here. Using kali. I am getting no results with an error;
`Process GoogleEnum-4:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3/dist-packages/sublist3r.py", line 269, in run
    domain_list = self.enumerate()
  File "/usr/lib/python3/dist-packages/sublist3r.py", line 240, in enumerate
    if not self.check_response_errors(resp):
  File "/usr/lib/python3/dist-packages/sublist3r.py", line 304, in check_response_errors
    if (type(resp) is str or type(resp) is unicode) and 'Our systems have detected unusual traffic' in resp:
NameError: name 'unicode' is not defined
HTTPSConnectionPool(host='www.virustotal.com', port=443): Max retries exceeded with url: /ui/domains/google.com/subdomains (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6d71d2b010>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
Process Virustotal-9:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3/dist-packages/sublist3r.py", line 269, in run
    domain_list = self.enumerate()
  File "/usr/lib/python3/dist-packages/sublist3r.py", line 703, in enumerate
    resp = json.loads(resp)
  File "/usr/lib/python3.10/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not int
HTTPSConnectionPool(host='searchdns.netcraft.com', port=443): Max retries exceeded with url: /?restriction=site+ends+with&host=google.com (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f6d71d2aec0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
Process NetcraftEnum-7:
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3/dist-packages/sublist3r.py", line 269, in run
    domain_list = self.enumerate()
  File "/usr/lib/python3/dist-packages/sublist3r.py", line 575, in enumerate
    if 'Next Page' not in resp:
TypeError: argument of type 'int' is not iterable
`

**Comment by huntergregal** [comment]
You can try my fork here: https://github.com/huntergregal/Sublist3r

But you should not be getting any major issues with the the original branch besides VirusTotal failures

**Comment by AhmadHatziq** [comment]
@huntergregal For some reason, your fork works and not the original. This is for my own setup (running Python on Windows). Thanks!

**Comment by Rohinish69** [comment]
> You can try my fork here: https://github.com/huntergregal/Sublist3r
> 
> But you should not be getting any major issues with the the original branch besides VirusTotal failures

Thx it is working
