### ISSUE TITLE
no module named 'requests'

### ISSUE THREAD

**Issue by Hanzo96** [aboul3la/Sublist3r#358]
hello, I'm trying to find subdomains of an app but it always throws this error

Traceback (most recent call last):
  File "/usr/bin/sublist3r", line 33, in <module>
    sys.exit(load_entry_point('Sublist3r==1.0', 'console_scripts', 'sublist3r')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/sublist3r", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/sublist3r.py", line 23, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

**Comment by hellodarkness** [comment]
You need to install requests.

Try the following on the command line: 

`pip install requests`

Or:

`pip3 install requests`

**Comment by KerberoSec** [comment]
use the command """""""""""""""""""""""""""""pip install requests""""""""""""""""""""""""
