### ISSUE TITLE
File "/usr/lib/python3/dist-packages/dns/resolver.py", line 1106, in nameservers. NotImplementedError

### ISSUE THREAD

**Issue by NobinPegasus** [aboul3la/Sublist3r#370]
When I'm enumerating I get the following error:

```
Process lookup-21:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/dns/resolver.py", line 1106, in nameservers
    raise NotImplementedError
NotImplementedError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/pegasus/Documents/Sublist3r/subbrute/subbrute.py", line 334, in run
    response = self.check(hostname, record_type)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pegasus/Documents/Sublist3r/subbrute/subbrute.py", line 221, in check
    self.resolver.nameservers += self.get_ns()
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/dns/resolver.py", line 1108, in nameservers
    raise ValueError(
ValueError: nameserver False is not an IP address or valid https URL
^CKilled
```
The script runs for a while. But after some time, it throws the above error.
My python version is `3.11.4`

The command I'm using: `python3 sublist3r.py -v -b -d <domain_name> -t 50`

**Comment by NobinPegasus** [comment]
The issue is resolved. I was running curl command at the same time on another terminal.
Running standalone sublist3r worked fine.
