### ISSUE TITLE
It stops after sowing virustotal error

### ISSUE THREAD

**Issue by rishixpress** [aboul3la/Sublist3r#380]
When I was using it for a long time it always worked, it shows Virustotal error and then starts showing subdomains, but today it stopped after showing Virustotal is blocking our request,It takes 10-20seconds and exits itself.

**Comment by Huzzla101** [comment]
Did u find any solutions ? i get this first when starting up program :
/home/mastermind/Sublist3r/sublist3r.py:75: SyntaxWarning: invalid escape sequence '\_'
  print("""%s
/home/mastermind/Sublist3r/sublist3r.py:286: SyntaxWarning: invalid escape sequence '\/'
  link_regx = re.compile('<cite.*?>(.*?)<\/cite>')
/home/mastermind/Sublist3r/sublist3r.py:343: SyntaxWarning: invalid escape sequence '\/'
  link = re.sub("<(\/)?b>", "", link)
  
  THEN program starts i start search and this come:
  
                  # Coded By Ahmed Aboul-Ela - @aboul3la

Usage: python sublist3r.py [Options] use -h for help
Error: the following arguments are required: -d/--domain
mastermind@GRANDM:~/Sublist3r$ python3 sublist3r.py -d www.vg.no
/home/mastermind/Sublist3r/sublist3r.py:75: SyntaxWarning: invalid escape sequence '\_'
  print("""%s
/home/mastermind/Sublist3r/sublist3r.py:286: SyntaxWarning: invalid escape sequence '\/'
  link_regx = re.compile('<cite.*?>(.*?)<\/cite>')
/home/mastermind/Sublist3r/sublist3r.py:343: SyntaxWarning: invalid escape sequence '\/'
  link = re.sub("<(\/)?b>", "", link)
/home/mastermind/Sublist3r/sublist3r.py:439: SyntaxWarning: invalid escape sequence '\/'
  link = re.sub('<(\/)?strong>|<span.*?>|<|>', '', link)
/home/mastermind/Sublist3r/sublist3r.py:658: SyntaxWarning: invalid escape sequence '\/'
  tbl_regex = re.compile('<a name="hostanchor"><\/a>Host Records.*?<table.*?>(.*?)</table>', re.S)
/home/mastermind/Sublist3r/sublist3r.py:898: SyntaxWarning: invalid escape sequence '\-'
  domain_check = re.compile("^(http|https)?[a-zA-Z0-9]+([\-\.]{1}[a-zA-Z0-9]+)*\.[a-zA-Z]{2,}$")

                 ____        _     _ _     _   _____
                / ___| _   _| |__ | (_)___| |_|___ / _ __
                \___ \| | | | '_ \| | / __| __| |_ \| '__|
                 ___) | |_| | |_) | | \__ \ |_ ___) | |
                |____/ \__,_|_.__/|_|_|___/\__|____/|_|

                # Coded By Ahmed Aboul-Ela - @aboul3la

[-] Enumerating subdomains now for www.vg.no
[-] Searching now in Baidu..
[-] Searching now in Yahoo..
[-] Searching now in Google..
[-] Searching now in Bing..
[-] Searching now in Ask..
[-] Searching now in Netcraft..
[-] Searching now in DNSdumpster..
[-] Searching now in Virustotal..
[-] Searching now in ThreatCrowd..
[-] Searching now in SSL Certificates..
[-] Searching now in PassiveDNS..
Process DNSdumpster-8:
Traceback (most recent call last):
  File "/usr/lib/python3.12/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/mastermind/Sublist3r/sublist3r.py", line 268, in run
    domain_list = self.enumerate()
                  ^^^^^^^^^^^^^^^^
  File "/home/mastermind/Sublist3r/sublist3r.py", line 647, in enumerate
    token = self.get_csrftoken(resp)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mastermind/Sublist3r/sublist3r.py", line 641, in get_csrftoken
    token = csrf_regex.findall(resp)[0]
            ~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
[!] Error: Virustotal probably now is blocking our requests
