### ISSUE TITLE
please what should i do in this case?

### ISSUE THREAD

**Issue by AmaniToamaWebDevelp1** [aboul3la/Sublist3r#382]
I try to run turbolist3r.py, where I have installed all dependencies what I need to run but I got this error

https://github.com/fleetcaptain/Turbolist3r

I use virtual machine hyper -v manager ubentu 22.04LTS

`(venv) sndibad@sndibad-Virtual-Machine:~/Turbolist3r$ python3 turbolist3r.py -d hackthebox.eu

           _____            _           _ _     _   _____
          |_   _|_   _ _ __| |__  ____ | (_)___| |_|___ / _ __
            | | | | | | `__|  _ \/    \| | / __| __| |_ \| '__|
            | | | \_| | |  | |_) | () || | \__ \ |_ ___) | |
            |_|  \____|_|  |_.__/\____/|_|_|___/\__|____/|_|

          # Based on Sublist3r by Ahmed Aboul-Ela - @aboul3la
          # Forked by Carl Pearson - github.com/fleetcaptain
    
[-] Enumerating subdomains now for hackthebox.eu
[-] Searching now in Baidu..
[-] Searching now in Yahoo..
[-] Searching now in Google..
[-] Searching now in Bing..
[-] Searching now in Ask..
[-] Searching now in Netcraft..
[-] Searching now in DNSdumpster..
[-] Searching now in Virustotal..
[-] Searching now in ThreatCrowd..
[-] Searching now in SSL Certificates..
[-] Searching now in PassiveDNS..
Process AskEnum-6:
Traceback (most recent call last):
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/sndibad/Turbolist3r/turbolist3r.py", line 309, in run
    domain_list = self.enumerate()
                  ^^^^^^^^^^^^^^^^
  File "/home/sndibad/Turbolist3r/turbolist3r.py", line 282, in enumerate
    links = self.extract_domains(resp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sndibad/Turbolist3r/turbolist3r.py", line 442, in extract_domains
    return links_list
           ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'links_list' where it is not associated with a value
HTTPSConnectionPool(host='www.virustotal.com', port=443): Max retries exceeded with url: /en/domain/hackthebox.eu/information/ (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fc4e53ffb10>: Failed to resolve 'www.virustotal.com' ([Errno -3] Temporary failure in name resolution)"))
HTTPSConnectionPool(host='searchdns.netcraft.com', port=443): Max retries exceeded with url: /?restriction=site+ends+with&host=example.com (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7fc4e53ffb10>: Failed to resolve 'searchdns.netcraft.com' ([Errno -3] Temporary failure in name resolution)"))
Process NetcraftEnum-7:
Process GoogleEnum-4:
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/sndibad/Turbolist3r/turbolist3r.py", line 309, in run
    domain_list = self.enumerate()
                  ^^^^^^^^^^^^^^^^
  File "/home/sndibad/Turbolist3r/turbolist3r.py", line 606, in enumerate
    cookies = self.get_cookies(resp.headers)
                               ^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'headers'
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/home/sndibad/Turbolist3r/turbolist3r.py", line 309, in run
    domain_list = self.enumerate()
                  ^^^^^^^^^^^^^^^^
  File "/home/sndibad/Turbolist3r/turbolist3r.py", line 280, in enumerate
    if not self.check_response_errors(resp):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sndibad/Turbolist3r/turbolist3r.py", line 343, in check_response_errors
    if (type(resp) is str or type(resp) is unicode) and 'Our systems have detected unusual traffic' in resp:
                                           ^^^^^^^
NameError: name 'unicode' is not defined
HTTPConnectionPool(host='ptrarchive.com', port=80): Max retries exceeded with url: /tools/search.htm?label=hackthebox.eu (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fc4e53ffb10>, 'Connection to ptrarchive.com timed out. (connect timeout=25)'))`

**Comment by AmaniToamaWebDevelp1** [comment]
When i connect to the home router the script does work with error, but when I connect my laptop to my mobile hotspot the script does not work, so whah is the reason in this case?

**Comment by AmaniToamaWebDevelp1** [comment]
When i connect to the home router the script is work with error, but when I connect my laptop to my mobile hotspot the script is not working, so whah is the reason in this case

**Comment by AmaniToamaWebDevelp1** [comment]
![Error.jpg](https://github.com/user-attachments/assets/4ca51178-0080-4df8-8871-3e12db97db50)

**Comment by AmaniToamaWebDevelp1** [comment]
Not the last trying is on the version 1.1

**Comment by AmaniToamaWebDevelp1** [comment]
I just try the same thing where i have  my router wifi connection for the old version, but when i connect to mobile hotspot the script does not work!
![Error1.jpg](https://github.com/user-attachments/assets/97867143-7393-43a5-95a6-65e618cf882d)

**Comment by AmaniToamaWebDevelp1** [comment]
Note:
When I change the security of my hotspot to WPA2-Personal, I got the same result of wifi router

**Comment by VickytheWicked** [comment]
Did you get the fix? I am facing the same issues
