### ISSUE TITLE
Error - Whar should I do, please?

### ISSUE THREAD

**Issue by lolagary** [aboul3la/Sublist3r#384]
I am getting this error, how can I solve, please? I am using python 3.13 on w11

PS C:\Users\Lola Gary\Desktop\Sublist3r-master\Sublist3r-master> python sublist3r.py -d google.com
C:\Users\Lola Gary\Desktop\Sublist3r-master\Sublist3r-master\sublist3r.py:75: SyntaxWarning: invalid escape sequence '\_'
  print("""%s
C:\Users\Lola Gary\Desktop\Sublist3r-master\Sublist3r-master\sublist3r.py:286: SyntaxWarning: invalid escape sequence '\/'
  link_regx = re.compile('<cite.*?>(.*?)<\/cite>')
C:\Users\Lola Gary\Desktop\Sublist3r-master\Sublist3r-master\sublist3r.py:343: SyntaxWarning: invalid escape sequence '\/'
  link = re.sub("<(\/)?b>", "", link)
C:\Users\Lola Gary\Desktop\Sublist3r-master\Sublist3r-master\sublist3r.py:439: SyntaxWarning: invalid escape sequence '\/'
  link = re.sub('<(\/)?strong>|<span.*?>|<|>', '', link)
C:\Users\Lola Gary\Desktop\Sublist3r-master\Sublist3r-master\sublist3r.py:658: SyntaxWarning: invalid escape sequence '\/'
  tbl_regex = re.compile('<a name="hostanchor"><\/a>Host Records.*?<table.*?>(.*?)</table>', re.S)
C:\Users\Lola Gary\Desktop\Sublist3r-master\Sublist3r-master\sublist3r.py:898: SyntaxWarning: invalid escape sequence '\-'
  domain_check = re.compile("^(http|https)?[a-zA-Z0-9]+([\-\.]{1}[a-zA-Z0-9]+)*\.[a-zA-Z]{2,}$")

                 ____        _     _ _     _   _____
                / ___| _   _| |__ | (_)___| |_|___ / _ __
                \___ \| | | | '_ \| | / __| __| |_ \| '__|
                 ___) | |_| | |_) | | \__ \ |_ ___) | |
                |____/ \__,_|_.__/|_|_|___/\__|____/|_|

                # Coded By Ahmed Aboul-Ela - @aboul3la

[-] Enumerating subdomains now for google.com
[-] Searching now in Baidu..
[-] Searching now in Yahoo..
[-] Searching now in Google..
[-] Searching now in Bing..
[-] Searching now in Ask..
[-] Searching now in Netcraft..
[-] Searching now in DNSdumpster..
[-] Searching now in Virustotal..
[-] Searching now in ThreatCrowd..
[-] Searching now in SSL Certificates..
[-] Searching now in PassiveDNS..
Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Users\Lola Gary\AppData\Local\Programs\Python\Python313\Lib\threading.py", line 1041, in _bootstrap_inner
    self.run()
    ~~~~~~~~^^
  File "C:\Users\Lola Gary\Desktop\Sublist3r-master\Sublist3r-master\sublist3r.py", line 268, in run
    domain_list = self.enumerate()
  File "C:\Users\Lola Gary\Desktop\Sublist3r-master\Sublist3r-master\sublist3r.py", line 647, in enumerate
    token = self.get_csrftoken(resp)
  File "C:\Users\Lola Gary\Desktop\Sublist3r-master\Sublist3r-master\sublist3r.py", line 641, in get_csrftoken
    token = csrf_regex.findall(resp)[0]
            ~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

**Comment by RashdanAhmed** [comment]
### I do also get the same issue, this started to occur very recently. Please rectify this issue as soon as possible

**This is the error I'm receiving when I run the tool**

Process DNSdumpster-8:                                                                                                       
Traceback (most recent call last):                                                                                           
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap                                             
    self.run()                                                                                                               
  File "/home/kali/.local/lib/python3.11/site-packages/sublist3r.py", line 268, in run                                       
    domain_list = self.enumerate()                                                                                           
                  ^^^^^^^^^^^^^^^^                                                                                           
  File "/home/kali/.local/lib/python3.11/site-packages/sublist3r.py", line 648, in enumerate                                 
    token = self.get_csrftoken(resp)                                                                                         
            ^^^^^^^^^^^^^^^^^^^^^^^^                                                                                         
  File "/home/kali/.local/lib/python3.11/site-packages/sublist3r.py", line 641, in get_csrftoken                             
    token = csrf_regex.findall(resp)[0]

**Comment by yavuzkuk** [comment]
You need to change some code parts. For example 286 at line you need to chance this code part.

`
link_regx = re.compile('<cite.?>(.?)</cite>')  ----> link_regx = re.compile(r'<cite.?>(.?)</cite>')
`

The "r" is important. It is a Python version problem.
