### ISSUE TITLE
Getting Error ------> token = csrf_regex.findall(resp)[0]  

### ISSUE THREAD

**Issue by RashdanAhmed** [aboul3la/Sublist3r#385]
### This is the error I get when I run the tool
**Please rectify the as soon as possible**

Process DNSdumpster-8:                                                                                                       
Traceback (most recent call last):                                                                                           
  File "/usr/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap                                             
    self.run()                                                                                                               
  File "/home/kali/.local/lib/python3.11/site-packages/sublist3r.py", line 268, in run                                       
    domain_list = self.enumerate()                                                                                           
                  ^^^^^^^^^^^^^^^^                                                                                           
  File "/home/kali/.local/lib/python3.11/site-packages/sublist3r.py", line 648, in enumerate                                 
    token = self.get_csrftoken(resp)                                                                                         
            ^^^^^^^^^^^^^^^^^^^^^^^^                                                                                         
  File "/home/kali/.local/lib/python3.11/site-packages/sublist3r.py", line 641, in get_csrftoken                             
    token = csrf_regex.findall(resp)[0]                                                                                      
            ~~~~~~~~~~~~~~~~~~~~~~~~^^^                                                                                      
IndexError: list index out of range

**Comment by zachrousseau** [comment]
I am getting something very similar: 

```
Exception in thread Thread-7:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sublist3r.py", line 268, in run      
    domain_list = self.enumerate()
                  ^^^^^^^^^^^^^^^^
  File "C:\Users\User\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sublist3r.py", line 647, in enumerate
    token = self.get_csrftoken(resp)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\sublist3r.py", line 641, in get_csrftoken
    token = csrf_regex.findall(resp)[0]
            ~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
````

**Comment by zachrousseau** [comment]
Related issue: https://github.com/aboul3la/Sublist3r/issues/386#issue-2702382415

**Comment by zachrousseau** [comment]
Related issue: https://github.com/aboul3la/Sublist3r/issues/384#issue-2663424238

**Comment by teotimepacreau** [comment]
getting the same error on Debian 12
