### ISSUE TITLE
Type Error

### ISSUE THREAD

**Issue by yoshimo** [aboul3la/Sublist3r#48]
I was using this with the bruteforece option and 4 threads (not sure yet how many my connection can handle) and after a while i got this:

`Exception in thread Thread-18:
Traceback (most recent call last):
  File "C:\Program Files\Python35-32\lib\site-packages\dns\inet.py", line 104, i
n is_multicast
    first = ord(dns.ipv4.inet_aton(text)[0])
TypeError: ord() expected string of length 1, but int found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python35-32\lib\site-packages\dns\inet.py", line 108, i
n is_multicast
    first = ord(dns.ipv6.inet_aton(text)[0])
  File "C:\Program Files\Python35-32\lib\site-packages\dns\ipv6.py", line 153, i
n inet_aton
    raise dns.exception.SyntaxError
dns.exception.SyntaxError: Text input is malformed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python35-32\lib\threading.py", line 914, in _bootstrap_
inner
    self.run()
  File "C:\Users\Sam\Downloads\Sublist3r\subbrute\subbrute.py", line 334, in run

    response = self.check(hostname, record_type)
  File "C:\Users\Sam\Downloads\Sublist3r\subbrute\subbrute.py", line 299, in che
ck
    raise e
  File "C:\Users\Sam\Downloads\Sublist3r\subbrute\subbrute.py", line 227, in che
ck
    resp = self.resolver.query(host)
  File "C:\Program Files\Python35-32\lib\site-packages\dns\resolver.py", line 96
2, in query
    source_port=source_port)
  File "C:\Program Files\Python35-32\lib\site-packages\dns\query.py", line 243,
in udp
    (dns.inet.is_multicast(where) and
  File "C:\Program Files\Python35-32\lib\site-packages\dns\inet.py", line 111, i
n is_multicast
    raise ValueError
ValueError`

What does this want to tell me?

**Comment by Tycx2ry** [comment]
nice tool,thanks for sharing it. i got this:
```
[-] Total Unique Subdomains Found: 18
[-] Start port scan now for the following ports: 80,443,8080,81,82,8081,8082
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "sublist3r.py", line 880, in port_scan
    self.print_("%s%s%s - %sFound open ports:%s %s%s%s"%(G,host,W,R,W,Y,', '.join(openports),W))
AttributeError: portscan instance has no attribute 'print_'

Exception in thread Thread-18:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "sublist3r.py", line 880, in port_scan
    self.print_("%s%s%s - %sFound open ports:%s %s%s%s"%(G,host,W,R,W,Y,', '.join(openports),W))
AttributeError: portscan instance has no attribute 'print_'

```

**Comment by Martin2877** [comment]
I have the same problem.
