### ISSUE TITLE
everytime it prints error when run

### ISSUE THREAD

**Issue by irs4675** [aboul3la/Sublist3r#5]
everytime it prints error when run

```
[-] Searching now in DNSdumpster..
[Errno 1] _ssl.c:507: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\tools\Sublist3r-master\sublist3r.py", line 196, in run
    domain_list = self.enumerate()
  File "C:\tools\Sublist3r-master\sublist3r.py", line 164, in enumerate
    resp = self.send_req(query, page_no)
  File "C:\tools\Sublist3r-master\sublist3r.py", line 106, in send_req
    resp = self.session.get(url, headers=headers, timeout=self.timeout)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 447, in send
    raise SSLError(e, request=request)
SSLError: [Errno 1] _ssl.c:507: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

[Errno 1] _ssl.c:507: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
Exception in thread Thread-3:
Traceback (most recent call last):
  File "C:\Python27\lib\threading.py", line 810, in __bootstrap_inner
    self.run()
  File "C:\tools\Sublist3r-master\sublist3r.py", line 196, in run
    domain_list = self.enumerate()
  File "C:\tools\Sublist3r-master\sublist3r.py", line 164, in enumerate
    resp = self.send_req(query, page_no)
  File "C:\tools\Sublist3r-master\sublist3r.py", line 106, in send_req
    resp = self.session.get(url, headers=headers, timeout=self.timeout)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 447, in send
    raise SSLError(e, request=request)
SSLError: [Errno 1] _ssl.c:507: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```

**Comment by aboul3la** [comment]
it looks like you have something that intercept the SSL connections which makes the connection  untrusted , so if you are behind a firewalled network that intercepts the ssl traffic or you are using something like burp-suite you should disable it and the problem should be resolved.

**Comment by aboul3la** [comment]
also you can disable the SSL verification in sublist3r code but it will have a security issue as the traffic sent from python could be intercepted and watched by man in the middle attacker.

if you want do this despite it's security impact, you can use the attached code that use "verify=False" in req() function. 
**Download**: [sublist3r.txt](https://github.com/aboul3la/Sublist3r/files/71963/sublist3r.txt)
Rename it to sublist3r.py and use it :)
