### ISSUE TITLE
dns resolver/message error

### ISSUE THREAD

**Issue by PareshParmar** [aboul3la/Sublist3r#66]
Hi,
it was working fine, having this issue since two days.
![screenshot 2563](https://cloud.githubusercontent.com/assets/9366817/22256004/52037054-e27f-11e6-9a38-7154be6d4729.png)

error:
```
[Traceback (most recent call last):
  File "E:\Sublist3r\sublist3r.py", line 20, in <module>
    from subbrute import subbrute
  File "E:\Sublist3r\subbrute\subbrute.py", line 18, in <module>
    import dns.resolver
  File "C:\Users\paresh\AppData\Roaming\Python\Python27\site-packages\dns\resolver.py", line 35, in <module>
    import dns.message
  File "C:\Users\paresh\AppData\Roaming\Python\Python27\site-packages\dns\message.py", line 191
    print('id %d' % self.id, file=s)
                                 ^
SyntaxError: invalid syntax
```
my python version: 2.7 
dnspython==1.15.0

same type of issue: https://github.com/byt3bl33d3r/MITMf/issues/245
any solution for this ?

Thanks

**Comment by aboul3la** [comment]
Hi @PareshParmar, seems you were using a newer dnspython module for python3 while running the tool on python 2.7, so please install the correct version of dnspython that works for python 2.7 .
