### ISSUE TITLE
Hey The scan stops after about 10 seconds, And I get a message like this ...

### ISSUE THREAD

**Issue by yf007** [aboul3la/Sublist3r#78]
Traceback (most recent call last):
  File "sublist3r.py", line 1025, in <module>
    res = main(domain, threads, savefile, ports, silent=False, verbose=verbose, enable_bruteforce=enable_bruteforce, engines=engines)
  File "sublist3r.py", line 971, in main
    enum.join()
  File "C:\Python27.007\lib\threading.py", line 940, in join
    self.__block.wait()
  File "C:\Python27.007\lib\threading.py", line 340, in wait
    waiter.acquire()
KeyboardInterrupt

**Comment by jeremyn** [comment]
`KeyboardInterrupt` usually means you quit the program using `Ctrl-C` while it was running. See [the Python documentation](https://docs.python.org/2/library/exceptions.html#exceptions.KeyboardInterrupt) for a slightly longer description.
