### ISSUE TITLE
Baidu - Subdomain Enum issue

### ISSUE THREAD

**Issue by Os3r3um** [aboul3la/Sublist3r#80]
Hi, 

Trying to use your tool I got this erro just seconds after I start the process: 

"
Process BaiduEnum-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "sublist3r.py", line 264, in run
    domain_list = self.enumerate()
  File "sublist3r.py", line 237, in enumerate
    links = self.extract_domains(resp)
  File "sublist3r.py", line 489, in extract_domains
    return links
UnboundLocalError: local variable 'links' referenced before assignment
"
Any idea how to fix this? 

Cheers.

**Comment by hannestrunde** [comment]
See #82 for a workaround..
