### ISSUE TITLE
not scan 

### ISSUE THREAD

**Issue by lnkakalink** [aboul3la/Sublist3r#81]
root@kali:~/Sublist3r-master# ./sublist3r.py -d 1

                 ____        _     _ _     _   _____
                / ___| _   _| |__ | (_)___| |_|___ / _ __
                \___ \| | | | '_ \| | / __| __| |_ \| '__|
                 ___) | |_| | |_) | | \__ \ |_ ___) | |
                |____/ \__,_|_.__/|_|_|___/\__|____/|_|

                # Coded By Ahmed Aboul-Ela - @aboul3la
    
[-] Enumerating subdomains now for 1
[-] Searching now in Baidu..
[-] Searching now in Yahoo..
[-] Searching now in Google..
[-] Searching now in Bing..
[-] Searching now in Ask..
[-] Searching now in Netcraft..
[-] Searching now in DNSdumpster..
[-] Searching now in Virustotal..
[-] Searching now in ThreatCrowd..
[-] Searching now in SSL Certificates..
[-] Searching now in PassiveDNS..
HTTPSConnectionPool(host='searchdns.netcraft.com', port=443): Max retries exceeded with url: /?restriction=site+ends+with&host=example.com (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7ff2b757b610>: Failed to establish a new connection: [Errno -2] Name or service not known',))
Process GoogleEnum-4:
Process BaiduEnum-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "./sublist3r.py", line 251, in run
    domain_list = self.enumerate()
  File "./sublist3r.py", line 251, in run
    domain_list = self.enumerate()
  File "./sublist3r.py", line 224, in enumerate
    links = self.extract_domains(resp)
  File "./sublist3r.py", line 476, in extract_domains
    return links
UnboundLocalError: local variable 'links' referenced before assignment
  File "./sublist3r.py", line 222, in enumerate
    if not self.check_response_errors(resp):
  File "./sublist3r.py", line 285, in check_response_errors
    if 'Our systems have detected unusual traffic' in resp:
TypeError: argument of type 'int' is not iterable
Process BingEnum-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "./sublist3r.py", line 251, in run
    domain_list = self.enumerate()
Process NetcraftEnum-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "./sublist3r.py", line 224, in enumerate
    links = self.extract_domains(resp)
  File "./sublist3r.py", line 251, in run
    domain_list = self.enumerate()
  File "./sublist3r.py", line 430, in extract_domains
    return links_list
UnboundLocalError: local variable 'links_list' referenced before assignment
  File "./sublist3r.py", line 551, in enumerate
    cookies = self.get_cookies(resp.headers)
AttributeError: 'NoneType' object has no attribute 'headers'
HTTPSConnectionPool(host='dnsdumpster.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7ff2b757b610>: Failed to establish a new connection: [Errno -2] Name or service not known',))
Process AskEnum-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "./sublist3r.py", line 251, in run
    domain_list = self.enumerate()
  File "./sublist3r.py", line 224, in enumerate
    links = self.extract_domains(resp)
  File "./sublist3r.py", line 382, in extract_domains
    return links_list
UnboundLocalError: local variable 'links_list' referenced before assignment
Process DNSdumpster-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "./sublist3r.py", line 251, in run
    domain_list = self.enumerate()
  File "./sublist3r.py", line 634, in enumerate
    token = self.get_csrftoken(resp)
  File "./sublist3r.py", line 629, in get_csrftoken
    token = csrf_regex.findall(resp)[0]
TypeError: expected string or buffer
HTTPConnectionPool(host='ptrarchive.com', port=80): Max retries exceeded with url: /tools/search.htm?label=qiwi.com (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7ff2b757b710>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPSConnectionPool(host='www.virustotal.com', port=443): Max retries exceeded with url: /en/domain/qiwi.com/information/ (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7ff2b757b610>: Failed to establish a new connection: [Errno -2] Name or service not known',))

**Comment by hannestrunde** [comment]
See #82 for a workaround..

**Comment by MythHack** [comment]
Use a shadowsocks like a global proxy

**Comment by Alaponuke** [comment]
this tool does not work at all I have the latest version of kali and there is no way that it works
