### ISSUE TITLE
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap

### ISSUE THREAD

**Issue by wifislax** [aboul3la/Sublist3r#82]
Process AskEnum-6:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "sublist3r.py", line 264, in run
    domain_list = self.enumerate()
  File "sublist3r.py", line 237, in enumerate
    links = self.extract_domains(resp)
  File "sublist3r.py", line 395, in extract_domains
    return links_list
UnboundLocalError: local variable 'links_list' referenced before assignment
Process GoogleEnum-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "sublist3r.py", line 264, in run
    domain_list = self.enumerate()
  File "sublist3r.py", line 235, in enumerate
    if not self.check_response_errors(resp):
  File "sublist3r.py", line 298, in check_response_errors
    if 'Our systems have detected unusual traffic' in resp:
TypeError: argument of type 'int' is not iterable

**Comment by hannestrunde** [comment]
A workaround is to only use engines which throw no errors:

`python sublist3r.py -d domain.com -t 100 -v -e "yahoo,google,bing,virustotal,threatcrowd,ssl,baidu,dnsdumpster" -o dns_discover.txt`

Sometimes dnsdumpster also throws errors so maybe leave this one out as well..

**Comment by altkdub** [comment]
getting similar errors on a fresh clone.
[-] Searching now in SSL Certificates..
[-] Searching now in PassiveDNS..
HTTPSConnectionPool(host='dnsdumpster.com', port=443): Read timed out. (read timeout=25)
Process DNSdumpster-8:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/tools/DNS/Sublist3r/sublist3r.py", line 264, in run
    domain_list = self.enumerate()
  File "/home/tools/DNS/Sublist3r/sublist3r.py", line 637, in enumerate
    self.extract_domains(post_resp)
  File "/home/tools/DNS/Sublist3r/sublist3r.py", line 649, in extract_domains
    results_tbl = tbl_regex.findall(resp)[0]
TypeError: expected string or buffer
HTTPConnectionPool(host='toolbar.netcraft.com', port=80): Read timed out. (read timeout=25)
Process NetcraftEnum-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/home/tools/DNS/Sublist3r/sublist3r.py", line 264, in run
    domain_list = self.enumerate()
  File "/home/tools/DNS/Sublist3r/sublist3r.py", line 561, in enumerate
    self.extract_domains(resp)
  File "/home/tools/DNS/Sublist3r/sublist3r.py", line 581, in extract_domains
    return links_list
UnboundLocalError: local variable 'links_list' referenced before assignment
[-] Starting bruteforce module now using subbrute..

**Comment by altkdub** [comment]
just figured out that it was because i was throwing a subdomain at it.  e.g. instead of company.com, us.company.com
it didn't find any us.... subdomains on the intial search, is there a way to feed it some known subdomain branches?

**Comment by MuhammadAbubakar** [comment]
how to resolve this error
