### ISSUE TITLE
No module named engines.engine

### ISSUE THREAD

**Issue by dipadas** [aboul3la/Sublist3r#88]
getting this error

  File "./sublist3r.py", line 26, in <module>
    from subscann3r import SubScann3r
  File "/root/Sublist3r/subscann3r.py", line 13, in <module>
    from engines.engine import Engines
ImportError: No module named engines.engine

**Comment by Plazmaz** [comment]
So this error actually stems from my fork of the repo, which hasn't been merged yet, so I'll try to help you diagnose it. How did you download sublist3r?

**Comment by Plazmaz** [comment]
Should be resolved in latest version. In the future, you should open issues about my fork on the page for that repo(will update readme):
https://github.com/Plazmaz/Sublist3r/

**Comment by dipadas** [comment]
@Plazmaz  the issue fixed but another syntax error is there now 

Traceback (most recent call last):
  File "sublist3r.py", line 26, in <module>
    from subscann3r import SubScann3r
  File "C:\Users\Dipak\Desktop\scripts\Sublist3r\subscann3r.py", line 6, in <module>
    from engines.engine import Engines
  File "C:\Users\Dipak\Desktop\scripts\Sublist3r\engines\engine.py", line 28
    def __init__(self, base_url: str, engine_name: str, domain: str, subdomains: list = None, q: list = None, lock: threading.Lock = threading.Lock(),
                               ^
SyntaxError: invalid syntax

**Comment by Plazmaz** [comment]
@dipadas going back to the original question, what version of python are you using?

**Comment by Plazmaz** [comment]
Alright, the issue should be resolved.

**Comment by dipadas** [comment]
@Plazmaz  its Fixed thanks :)

**Comment by dipadas** [comment]
again this issue arises 
[-] Searching now in Baidu..
[-] Searching now in Google..
[-] Searching now in Virustotal..
[-] Searching now in Yahoo..
[-] Searching now in Netcraft..
[-] Searching now in SSL Certificates..
[-] Searching now in Ask..
[-] Searching now in ThreatCrowd..
[-] Searching now in DNSdumpster..
[-] Searching now in Bing..
[-] Searching now in PassiveDNS..
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.81 Safari/537.36
Traceback (most recent call last):
  File "./sublist3r.py", line 98, in <module>
    takeover_check=takeover_check, engines=engines)
  File "./sublist3r.py", line 79, in main
    return scanner.scan()
  File "/root/Sublist3r/subscann3r.py", line 111, in scan
    subdomains = sorted(subdomains, key=Util.subdomain_sorting_key)
TypeError: unbound method subdomain_sorting_key() must be called with Util instance as first argument (got unicode instance instead)

**Comment by Plazmaz** [comment]
What's the command you're using for that @d1pakda5? (sorry for the delayed response)
